"""
VidRush compliance guard: reduce reused-content and copyright-strike risk by
requiring original or properly licensed inputs before publication.

Policy posture:
- YouTube monetization favors original creation and can reject reused,
  repetitive, or mass-produced content.
- Instagram/Threads expect posted media to be created by the account owner or
  used with rights.
- X/Twitter can restrict duplicative or substantially similar automated posts.

This module is VidRush-only. It does NOT touch the money-maker blog.
"""
import os
import hashlib
import json
import re

OUTPUT_DIR = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "output", "vidrush")
SEEN_DB = os.path.join(OUTPUT_DIR, "_compliance_seen.json")

ORIGINAL_VISUAL_SOURCES = {
    "ai_generator",
    "ai_image",
    "pollinations",
    "replicate",
    "original_motion_graphics",
}
GENERATED_FALLBACK_SOURCES = {
    "ffmpeg_motion",
    "ffmpeg_synthetic",
}
LICENSED_STOCK_SOURCES = {
    "pexels",
    "pexels.com",
    "coverr",
}
LICENSED_LOCAL_SOURCES = {
    "local",
    "licensed_local",
    "royalty_free_local",
}
ORIGINAL_LICENSE_TYPES = {
    "original_ai_generated",
    "original_motion_graphics",
    "original_synthetic",
    "owned_asset",
}
LICENSED_STOCK_LICENSE_TYPES = {
    "pexels_license",
    "coverr_license",
    "licensed_stock",
    "royalty_free_license",
    "creative_commons",
    "public_domain",
}
LICENSED_LOCAL_LICENSE_TYPES = {
    "licensed_local",
    "local_asset_license",
    "royalty_free_license",
    "creative_commons",
    "public_domain",
}
LEGACY_GENERATED_LICENSE_TYPES = {
    "public_domain",
}
GENERIC_PROVENANCE_VALUES = {
    "",
    "cloud",
    "local",
    "none",
    "n/a",
    "stock",
    "unknown",
}
RIGHTS_OBFUSCATION_PATTERNS = [
    re.compile(pattern, re.IGNORECASE)
    for pattern in (
        r"\b(content\s*id|copyright|rights)\b.{0,48}\b(bypass|evad|avoid\s+detection|hide\s+from|trick)\b",
        r"\b(bypass|evad|avoid\s+detection|hide\s+from|trick)\b.{0,48}\b(content\s*id|copyright|rights)\b",
        r"\bfingerprint\b.{0,48}\b(evad|mask|hide|avoid|trick)\b",
        r"\b(pitch|mirror|flip)\b.{0,48}\b(content\s*id|copyright|rights|detection)\b",
    )
]


def _load_seen():
    if os.path.exists(SEEN_DB):
        try:
            return json.load(open(SEEN_DB))
        except Exception:
            return {}
    return {}


def _save_seen(d):
    try:
        json.dump(d, open(SEEN_DB, "w"), indent=2)
    except Exception:
        pass


def record_published_script(title, script_text):
    """Record a script only after a caller has confirmed publication."""
    seen = _load_seen()
    script_hash = hashlib.md5(script_text.strip().encode()).hexdigest()
    seen[script_hash] = title
    _save_seen(seen)


def _norm(value):
    return str(value or "").strip().lower()


def _has_specific_provenance(item):
    for key in ("url", "source_path", "license_url", "provenance"):
        value = _norm(item.get(key))
        if value and value not in GENERIC_PROVENANCE_VALUES:
            return True
    return False


def find_rights_obfuscation_language(*values):
    """Return matched terms for instructions that try to hide rights issues."""
    text = " ".join(str(value or "") for value in values)
    return [
        match.group(0).strip()
        for pattern in RIGHTS_OBFUSCATION_PATTERNS
        for match in pattern.finditer(text)
    ]


def classify_asset_record(item):
    """
    Return (category, reason). category is "real", "fallback", or "blocked".
    "real" means original or licensed media; "fallback" means generated by this
    pipeline but still counted toward the repetitive-template fallback ratio.
    """
    if not isinstance(item, dict):
        return "blocked", "BAD_ASSET_RECORD: manifest item is not an object."

    source = _norm(item.get("source"))
    license_type = _norm(item.get("license_type"))
    asset_id = item.get("asset_id", "unknown")
    obfuscation_hits = find_rights_obfuscation_language(
        item.get("source"),
        item.get("license_type"),
        item.get("url"),
        item.get("provenance"),
        item.get("notes"),
    )

    if obfuscation_hits:
        return (
            "blocked",
            f"RIGHTS_OBFUSCATION_LANGUAGE: asset {asset_id} contains terms about hiding rights issues.",
        )

    if not source:
        return "blocked", f"MISSING_SOURCE: asset {asset_id} has no source."
    if not license_type:
        return "blocked", f"MISSING_LICENSE: asset {asset_id} has no license_type."

    if source in ORIGINAL_VISUAL_SOURCES:
        if license_type in ORIGINAL_LICENSE_TYPES:
            return "real", None
        return (
            "blocked",
            f"UNAPPROVED_LICENSE: asset {asset_id} source {source} uses license {license_type}.",
        )

    if source in GENERATED_FALLBACK_SOURCES:
        if license_type in ORIGINAL_LICENSE_TYPES or license_type in LEGACY_GENERATED_LICENSE_TYPES:
            return "fallback", None
        return (
            "blocked",
            f"UNAPPROVED_LICENSE: asset {asset_id} generated source {source} uses license {license_type}.",
        )

    if source in LICENSED_STOCK_SOURCES:
        if license_type not in LICENSED_STOCK_LICENSE_TYPES:
            return (
                "blocked",
                f"UNAPPROVED_LICENSE: asset {asset_id} stock source {source} uses license {license_type}.",
            )
        if not _has_specific_provenance(item):
            return (
                "blocked",
                f"MISSING_PROVENANCE: asset {asset_id} stock source {source} needs a URL or license proof.",
            )
        return "real", None

    if source in LICENSED_LOCAL_SOURCES:
        if license_type not in LICENSED_LOCAL_LICENSE_TYPES:
            return (
                "blocked",
                f"UNAPPROVED_LICENSE: asset {asset_id} local source uses license {license_type}.",
            )
        if not _has_specific_provenance(item):
            return (
                "blocked",
                f"MISSING_PROVENANCE: asset {asset_id} local asset needs source_path or license proof.",
            )
        return "real", None

    return "blocked", f"UNSAFE SOURCE DETECTED: {source}"


def check_asset_manifest(manifest):
    """Validate manifest asset records against original/licensed source rules."""
    reasons = []
    stats = {
        "real_count": 0,
        "fallback_count": 0,
        "licenses": set(),
    }

    if not isinstance(manifest, list):
        return False, ["MANIFEST_FORMAT: manifest must be a list of asset records."], stats

    for item in manifest:
        if isinstance(item, dict):
            stats["licenses"].add(str(item.get("license_type", "unknown") or "unknown"))
        category, reason = classify_asset_record(item)
        if category == "real":
            stats["real_count"] += 1
        elif category == "fallback":
            stats["fallback_count"] += 1
        else:
            stats["fallback_count"] += 1
        if reason:
            reasons.append(reason)

    return len(reasons) == 0, reasons, stats


def check_video_compliance(title, script_text, use_stock_footage, character_present):
    """
    Returns (ok, reasons[]).
    ok=False means the video violates a platform guideline and must NOT be posted.
    """
    reasons = []

    # 1. Must be original creation -> our cartoon host must be present
    if not character_present:
        reasons.append("NO_ORIGINAL_HOST: video has no identifiable original character; "
                       "risks YouTube 'reused content' / Instagram 'post only what you created'.")

    # 2. Stock footage only allowed as B-roll under original commentary (character)
    if use_stock_footage and not character_present:
        reasons.append("STOCK_WITHOUT_HOST: reused stock footage without original host = "
                       "reused-content violation.")

    obfuscation_hits = find_rights_obfuscation_language(title, script_text)
    if obfuscation_hits:
        reasons.append("RIGHTS_OBFUSCATION_LANGUAGE: rewrite title/script around original or licensed content.")

    # 3. No duplicative / mass-produced content: hash script, reject near-dupes
    seen = _load_seen()
    h = hashlib.md5(script_text.strip().encode()).hexdigest()
    if h in seen:
        reasons.append("DUPLICATE_SCRIPT: identical script already published (X/YT inauthentic policy).")

    # 4. Script must be substantive (not a 1-line reuse of someone's text)
    words = len(script_text.split())
    if words < 25:
        reasons.append(f"SCRIPT_TOO_SHORT ({words} words): looks like a repost, not original.")
    if use_stock_footage and words < 50:
        reasons.append(f"STOCK_COMMENTARY_TOO_SHORT ({words} words): stock B-roll needs substantial original commentary.")

    # 5. Title must not be clickbait-y all-caps spam
    if title.isupper() and len(title) > 12:
        reasons.append("CLICKBAIT_TITLE: all-caps spam title violates advertiser-friendly rules.")

    return (len(reasons) == 0, reasons)


def compliance_report(title, script_text, use_stock_footage, character_present):
    ok, reasons = check_video_compliance(title, script_text, use_stock_footage, character_present)
    status = "COMPLIANT" if ok else "BLOCKED"
    print(f"[compliance] {status}: {title}")
    for r in reasons:
        print(f"  - {r}")
    return ok


if __name__ == "__main__":
    # self test
    good = check_video_compliance(
        "पैसे बचाने के 3 आसान तरीके | Paisa Bhai",
        "नमस्ते दोस्तों! मैं पैसा भाई हूँ। आज बताएंगे पैसे बचाने के 3 आसान तरीके जो हर कोई अपना सकता है।",
        use_stock_footage=False, character_present=True)
    print("good ok:", good[0])
    bad = check_video_compliance(
        "MONEY TIPS", "short", use_stock_footage=True, character_present=False)
    print("bad ok:", bad[0], bad[1])
